"""add raw_sync_progress table

Revision ID: 5b8b60fff8da
Revises: 91bfe0529c3c
Create Date: 2026-02-17 00:37:25.605776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b8b60fff8da'
down_revision: Union[str, Sequence[str], None] = '91bfe0529c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_sync_progress',
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('sync_key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('record_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_retry_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('table_name', 'sync_key')
    )
    op.drop_index(op.f('idx_industry_member_con_code'), table_name='industry_member')
    op.drop_index(op.f('idx_industry_member_in_date'), table_name='industry_member')
    op.drop_index(op.f('idx_industry_member_index_code'), table_name='industry_member')
    op.drop_table('industry_member')
    op.drop_index(op.f('idx_index_daily_code_date'), table_name='index_daily')
    op.drop_index(op.f('idx_index_daily_trade_date'), table_name='index_daily')
    op.drop_table('index_daily')
    op.drop_index(op.f('idx_concept_technical_code_date'), table_name='concept_technical_daily')
    op.drop_index(op.f('idx_concept_technical_trade_date'), table_name='concept_technical_daily')
    op.drop_table('concept_technical_daily')
    op.drop_index(op.f('idx_index_weight_con_code'), table_name='index_weight')
    op.drop_index(op.f('idx_index_weight_index_code'), table_name='index_weight')
    op.drop_index(op.f('idx_index_weight_trade_date'), table_name='index_weight')
    op.drop_table('index_weight')
    op.drop_index(op.f('idx_concept_member_concept_code'), table_name='concept_member')
    op.drop_index(op.f('idx_concept_member_in_date'), table_name='concept_member')
    op.drop_index(op.f('idx_concept_member_stock_code'), table_name='concept_member')
    op.drop_table('concept_member')
    op.drop_table('industry_classify')
    op.drop_index(op.f('idx_index_technical_code_date'), table_name='index_technical_daily')
    op.drop_index(op.f('idx_index_technical_trade_date'), table_name='index_technical_daily')
    op.drop_table('index_technical_daily')
    op.drop_index(op.f('idx_concept_daily_code_date'), table_name='concept_daily')
    op.drop_index(op.f('idx_concept_daily_trade_date'), table_name='concept_daily')
    op.drop_table('concept_daily')
    op.drop_table('index_basic')
    op.drop_table('concept_index')
    op.drop_index(op.f('idx_dragon_tiger_code'), table_name='dragon_tiger')
    op.create_index('idx_dragon_tiger_code', 'dragon_tiger', ['ts_code', 'trade_date'], unique=False, postgresql_ops={'trade_date': 'DESC'})
    op.drop_index(op.f('idx_finance_code_date'), table_name='finance_indicator')
    op.create_index('idx_finance_code_date', 'finance_indicator', ['ts_code', 'end_date'], unique=False, postgresql_ops={'end_date': 'DESC'})
    op.alter_column('raw_tushare_stk_managers', 'resume',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('raw_tushare_stock_company', 'introduction',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('raw_tushare_stock_company', 'main_business',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('raw_tushare_stock_company', 'business_scope',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_stock_daily_code_date'), table_name='stock_daily')
    op.create_index('idx_stock_daily_code_date', 'stock_daily', ['ts_code', 'trade_date'], unique=False, postgresql_ops={'trade_date': 'DESC'})
    op.drop_index(op.f('idx_stock_min_code_time'), table_name='stock_min')
    op.create_index('idx_stock_min_code_time', 'stock_min', ['ts_code', 'trade_time'], unique=False, postgresql_ops={'trade_time': 'DESC'})
    op.drop_index(op.f('idx_technical_code_date'), table_name='technical_daily')
    op.create_index('idx_technical_code_date', 'technical_daily', ['ts_code', 'trade_date'], unique=False, postgresql_ops={'trade_date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_technical_code_date', table_name='technical_daily', postgresql_ops={'trade_date': 'DESC'})
    op.create_index(op.f('idx_technical_code_date'), 'technical_daily', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.drop_index('idx_stock_min_code_time', table_name='stock_min', postgresql_ops={'trade_time': 'DESC'})
    op.create_index(op.f('idx_stock_min_code_time'), 'stock_min', ['ts_code', sa.literal_column('trade_time DESC')], unique=False)
    op.drop_index('idx_stock_daily_code_date', table_name='stock_daily', postgresql_ops={'trade_date': 'DESC'})
    op.create_index(op.f('idx_stock_daily_code_date'), 'stock_daily', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.alter_column('raw_tushare_stock_company', 'business_scope',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('raw_tushare_stock_company', 'main_business',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('raw_tushare_stock_company', 'introduction',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('raw_tushare_stk_managers', 'resume',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('idx_finance_code_date', table_name='finance_indicator', postgresql_ops={'end_date': 'DESC'})
    op.create_index(op.f('idx_finance_code_date'), 'finance_indicator', ['ts_code', sa.literal_column('end_date DESC')], unique=False)
    op.drop_index('idx_dragon_tiger_code', table_name='dragon_tiger', postgresql_ops={'trade_date': 'DESC'})
    op.create_index(op.f('idx_dragon_tiger_code'), 'dragon_tiger', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('concept_index',
    sa.Column('ts_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('src', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ts_code', name=op.f('concept_index_pkey'))
    )
    op.create_table('index_basic',
    sa.Column('ts_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('fullname', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('market', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('index_type', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('base_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('base_point', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('list_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('weight_rule', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('desc', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('exp_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ts_code', name=op.f('index_basic_pkey'))
    )
    op.create_table('concept_daily',
    sa.Column('ts_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('high', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('low', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('close', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('pre_close', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('change', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('pct_chg', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('vol', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date', name=op.f('concept_daily_pkey'))
    )
    op.create_index(op.f('idx_concept_daily_trade_date'), 'concept_daily', ['trade_date'], unique=False)
    op.create_index(op.f('idx_concept_daily_code_date'), 'concept_daily', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('index_technical_daily',
    sa.Column('ts_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ma5', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma10', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma20', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma60', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma120', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma250', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_dif', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_dea', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_hist', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('kdj_k', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('kdj_d', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('kdj_j', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('rsi6', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('rsi12', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('rsi24', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('boll_upper', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('boll_mid', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('boll_lower', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('vol_ma5', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('vol_ma10', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('vol_ratio', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('atr14', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('cci14', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('willr14', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date', name=op.f('index_technical_daily_pkey'))
    )
    op.create_index(op.f('idx_index_technical_trade_date'), 'index_technical_daily', ['trade_date'], unique=False)
    op.create_index(op.f('idx_index_technical_code_date'), 'index_technical_daily', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('industry_classify',
    sa.Column('index_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('industry_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('industry_code', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('src', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('index_code', name=op.f('industry_classify_pkey'))
    )
    op.create_table('concept_member',
    sa.Column('concept_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('stock_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('in_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('out_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('concept_code', 'stock_code', 'in_date', name=op.f('concept_member_pkey'))
    )
    op.create_index(op.f('idx_concept_member_stock_code'), 'concept_member', ['stock_code'], unique=False)
    op.create_index(op.f('idx_concept_member_in_date'), 'concept_member', ['in_date'], unique=False)
    op.create_index(op.f('idx_concept_member_concept_code'), 'concept_member', ['concept_code'], unique=False)
    op.create_table('index_weight',
    sa.Column('index_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('con_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('index_code', 'con_code', 'trade_date', name=op.f('index_weight_pkey'))
    )
    op.create_index(op.f('idx_index_weight_trade_date'), 'index_weight', ['trade_date'], unique=False)
    op.create_index(op.f('idx_index_weight_index_code'), 'index_weight', ['index_code'], unique=False)
    op.create_index(op.f('idx_index_weight_con_code'), 'index_weight', ['con_code'], unique=False)
    op.create_table('concept_technical_daily',
    sa.Column('ts_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ma5', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma10', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma20', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma60', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma120', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('ma250', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_dif', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_dea', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('macd_hist', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('kdj_k', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('kdj_d', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('kdj_j', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('rsi6', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('rsi12', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('rsi24', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('boll_upper', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('boll_mid', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('boll_lower', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('vol_ma5', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('vol_ma10', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('vol_ratio', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('atr14', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('cci14', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('willr14', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date', name=op.f('concept_technical_daily_pkey'))
    )
    op.create_index(op.f('idx_concept_technical_trade_date'), 'concept_technical_daily', ['trade_date'], unique=False)
    op.create_index(op.f('idx_concept_technical_code_date'), 'concept_technical_daily', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('index_daily',
    sa.Column('ts_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('pre_close', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('change', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('pct_chg', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('vol', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=20, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date', name=op.f('index_daily_pkey'))
    )
    op.create_index(op.f('idx_index_daily_trade_date'), 'index_daily', ['trade_date'], unique=False)
    op.create_index(op.f('idx_index_daily_code_date'), 'index_daily', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.create_table('industry_member',
    sa.Column('index_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('con_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('in_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('out_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_new', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('index_code', 'con_code', 'in_date', name=op.f('industry_member_pkey'))
    )
    op.create_index(op.f('idx_industry_member_index_code'), 'industry_member', ['index_code'], unique=False)
    op.create_index(op.f('idx_industry_member_in_date'), 'industry_member', ['in_date'], unique=False)
    op.create_index(op.f('idx_industry_member_con_code'), 'industry_member', ['con_code'], unique=False)
    op.drop_table('raw_sync_progress')
    # ### end Alembic commands ###
