"""add P0 raw tushare tables

Revision ID: 7a0c7d9f66b5
Revises: c3a7e2d4f891
Create Date: 2026-02-15 00:23:34.358779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0c7d9f66b5'
down_revision: Union[str, Sequence[str], None] = 'c3a7e2d4f891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_tushare_adj_factor',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('adj_factor', sa.Numeric(precision=16, scale=6), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_index('idx_raw_adj_factor_trade_date', 'raw_tushare_adj_factor', ['trade_date'], unique=False)
    op.create_table('raw_tushare_daily',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pre_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pct_chg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('vol', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_index('idx_raw_daily_trade_date', 'raw_tushare_daily', ['trade_date'], unique=False)
    op.create_table('raw_tushare_daily_basic',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('turnover_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('turnover_rate_f', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pe', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('pe_ttm', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('pb', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('ps', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('ps_ttm', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('dv_ratio', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('dv_ttm', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('float_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('free_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('total_mv', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('circ_mv', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_index('idx_raw_daily_basic_trade_date', 'raw_tushare_daily_basic', ['trade_date'], unique=False)
    op.create_table('raw_tushare_stk_limit',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('pre_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('up_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('down_limit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_index('idx_raw_stk_limit_trade_date', 'raw_tushare_stk_limit', ['trade_date'], unique=False)
    op.create_table('raw_tushare_stock_basic',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=16), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('enname', sa.String(length=128), nullable=True),
    sa.Column('cnspell', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('exchange', sa.String(length=8), nullable=True),
    sa.Column('curr_type', sa.String(length=8), nullable=True),
    sa.Column('list_status', sa.String(length=4), nullable=True),
    sa.Column('list_date', sa.String(length=8), nullable=True),
    sa.Column('delist_date', sa.String(length=8), nullable=True),
    sa.Column('is_hs', sa.String(length=4), nullable=True),
    sa.Column('act_name', sa.String(length=64), nullable=True),
    sa.Column('act_ent_type', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('raw_tushare_trade_cal',
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('cal_date', sa.String(length=8), nullable=False),
    sa.Column('is_open', sa.String(length=4), nullable=True),
    sa.Column('pretrade_date', sa.String(length=8), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('exchange', 'cal_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_tushare_trade_cal')
    op.drop_table('raw_tushare_stock_basic')
    op.drop_index('idx_raw_stk_limit_trade_date', table_name='raw_tushare_stk_limit')
    op.drop_table('raw_tushare_stk_limit')
    op.drop_index('idx_raw_daily_basic_trade_date', table_name='raw_tushare_daily_basic')
    op.drop_table('raw_tushare_daily_basic')
    op.drop_index('idx_raw_daily_trade_date', table_name='raw_tushare_daily')
    op.drop_table('raw_tushare_daily')
    op.drop_index('idx_raw_adj_factor_trade_date', table_name='raw_tushare_adj_factor')
    op.drop_table('raw_tushare_adj_factor')
    # ### end Alembic commands ###
