"""add delist_date to stocks table

Revision ID: b8c91b1f1c27
Revises: 0de5d45e0673
Create Date: 2026-02-12 22:06:39.975791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8c91b1f1c27'
down_revision: Union[str, Sequence[str], None] = '0de5d45e0673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('backtest_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backtest_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('backtest_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_source_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_source_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('dragon_tiger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_dragon_tiger_code'), table_name='dragon_tiger')
    op.create_index('idx_dragon_tiger_code', 'dragon_tiger', ['ts_code', 'trade_date'], unique=False, postgresql_ops={'trade_date': 'DESC'})
    op.alter_column('finance_indicator', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('finance_indicator', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_finance_code_date'), table_name='finance_indicator')
    op.create_index('idx_finance_code_date', 'finance_indicator', ['ts_code', 'end_date'], unique=False, postgresql_ops={'end_date': 'DESC'})
    op.alter_column('money_flow', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_stock_daily_code_date', 'stock_daily', ['ts_code', 'trade_date'], unique=False, postgresql_ops={'trade_date': 'DESC'})
    op.create_index('idx_stock_daily_trade_date', 'stock_daily', ['trade_date'], unique=False)
    op.alter_column('stock_min', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_stock_min_code_time'), table_name='stock_min')
    op.create_index('idx_stock_min_code_time', 'stock_min', ['ts_code', 'trade_time'], unique=False, postgresql_ops={'trade_time': 'DESC'})
    op.add_column('stocks', sa.Column('delist_date', sa.Date(), nullable=True))
    op.alter_column('stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('technical_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('technical_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_technical_code_date'), table_name='technical_daily')
    op.create_index('idx_technical_code_date', 'technical_daily', ['ts_code', 'trade_date'], unique=False, postgresql_ops={'trade_date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_technical_code_date', table_name='technical_daily', postgresql_ops={'trade_date': 'DESC'})
    op.create_index(op.f('idx_technical_code_date'), 'technical_daily', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.alter_column('technical_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('technical_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('strategies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('stocks', 'delist_date')
    op.drop_index('idx_stock_min_code_time', table_name='stock_min', postgresql_ops={'trade_time': 'DESC'})
    op.create_index(op.f('idx_stock_min_code_time'), 'stock_min', ['ts_code', sa.literal_column('trade_time DESC')], unique=False)
    op.alter_column('stock_min', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_stock_daily_trade_date', table_name='stock_daily')
    op.drop_index('idx_stock_daily_code_date', table_name='stock_daily', postgresql_ops={'trade_date': 'DESC'})
    op.alter_column('stock_daily', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stock_daily', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('money_flow', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_finance_code_date', table_name='finance_indicator', postgresql_ops={'end_date': 'DESC'})
    op.create_index(op.f('idx_finance_code_date'), 'finance_indicator', ['ts_code', sa.literal_column('end_date DESC')], unique=False)
    op.alter_column('finance_indicator', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('finance_indicator', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_dragon_tiger_code', table_name='dragon_tiger', postgresql_ops={'trade_date': 'DESC'})
    op.create_index(op.f('idx_dragon_tiger_code'), 'dragon_tiger', ['ts_code', sa.literal_column('trade_date DESC')], unique=False)
    op.alter_column('dragon_tiger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_source_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('data_source_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backtest_tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backtest_tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backtest_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
